-*- mode:org; coding: utf-8  -*-
** К вопросу о сборке текста
*** Компиляция

Весь текст в koi8-r 

Можно воспользоваться Makefile (make dist делает и исходники и pdf)

Сборка заведомо проходит в рамках TeX Live 2011 в полной
установке. 

Необходимо доставить пакеты c CTAN, отсутствующие в TeX Live: floatflt
(проблемы с лицензией — автор испарился) и slashbox (исчез между TeX
Live 2009 и TeX Live 2011)

*** Отличия от оригинала
 Немного поменялось описание bytefield в соответствиями с изменениями
 пакета

 Ловля оторванных предлогов и переносов на другие страницы

 Исправление опечаток и ошибок (Клапейрон)

*** Проблемы сборки

Все картинки по возможности делались чёрно-белыми, так как была
ориентация на печать. Для электронной версии по хорошему нужен цвет.

*** Чего мне в бумажной книге не понравилось:

а) плохая бумага и расплывающийся кое-где шрифт

б) как прикреплён CD - оставляется клейкая полоса.
  
** Случайный ChangeLog

<2012-05-01 Вт.> Правки от Алексея Курносенко

Залил версию 1.01 Исправил поиск для Adobe Reader (cmap должен быть
выше выбора кодировки)


