-*- mode:org; coding: utf-8  -*-
** К вопросу о сборке текста
*** Компиляция

Весь текст в koi8-r 

Можно воспользоваться Makefile. Достаточно сказать make ctex.pdf
(лучше сразу трижды).

Сборка заведомо проходит в рамках TeX Live 2012 в полной
установке. 

*** К вопросу о Google Code

Информация по делу тут:
http://alblue.bandlem.com/2011/07/setting-up-google-code-with-git.html

Вкратце:
 * Настраивается ~/.netrc Информация для настройки берётся тут:
   https://code.google.com/hosting/settings В файл нужно написать
   что-то вроде (вместо ctex-ru, NAME и XXXXXX нужно подставить свою
   информацию):

-------------------------------------
machine ctex-ru.googlecode.com
login NAME@gmail.com
password XXXXXXXXXXXXXXXXXXX
machine wiki.ctex-ru.googlecode.com
login NAME@gmail.com
password XXXXXXXXXXXXXXXXXXX
-------------------------------------

 * Переходим в директорию git-проекта и набираем

> git remote add googlecode https://ctex-ru.googlecode.com/git
> git push googlecode master:master

*** Извлечение исходников

> git clone https://code.google.com/p/ctex-ru/

*** Работа с исходниками

Если работаешь один, то всё просто:

> git add <files>
> git commit -m "Причина изменений"
> git push googlecode

Несколько человек должны быть осторожнее в своих изменениях.


*** Отличия от оригинала
 Немного поменялось описание bytefield в соответствиями с изменениями
 пакета

 Ловля оторванных предлогов и переносов на другие страницы

 Исправление опечаток и ошибок (Клапейрон)

 Поправлена информация об оформлении библиографии по ГОСТу. Спасибо
И.А. Котельникову за обновление стилей gost2008  и gost2003

*** Проблемы сборки

Все картинки по возможности делались чёрно-белыми, так как была
ориентация на печать. Для электронной версии по хорошему нужен цвет.

*** Чего мне в бумажной книге не понравилось:

а) плохая бумага и расплывающийся кое-где шрифт

б) как прикреплён CD - оставляется клейкая полоса.
  
** Случайный ChangeLog

<2012-05-01 Вт.> Правки от Алексея Курносенко

Залил версию 1.01 Исправил поиск для Adobe Reader (cmap должен быть
выше выбора кодировки)

<2013-01-01 Вт.> Исправил информацию по оформлению библиографии по
ГОСТ -- вылезло +2 страницы. Теперь имеется расхождение нумерации с
книгой.

<2013-01-01 Вт.> Некоторые правки от Николая Велюрова.

