# -*- coding: koi8-r -*-
#
# Компиляция картинок classes
#
# 2012 (c)  Е.М. Балдин 
#

include ../rules.mk

#  classes-papertex.eps\
# classes-eskd.eps ExampleFrames.eps \
# classes-moderncv.eps classes-pecha.eps
PICS := 

all: $(PICS) 



include ../rules-post.mk

