# -*- coding: koi8-r -*-
#
# Компиляция картинок intro
#
# 2012 (c)  Е.М. Балдин 
#

include ../rules.mk

PICS :=  intro-1.eps

all:  $(PICS)

intro-1.eps: intro.mp
	$(PREFIX)$(MPOST) intro.mp

include ../rules-post.mk